In [1]:
import numpy as np

In [6]:
a = np.array([[[1,2,3],
             [3,-4,5],
             [5,6,7]], 
              [[6,2,-3],
             [3,7,5],
             [0,-6,7]]])
            

In [7]:
another_arr = a.reshape(-1, a.shape[0])
another_arr.shape

(9, 2)

In [8]:
np.maximum(a, np.zeros(a.shape))

array([[[ 1.,  2.,  3.],
        [ 3.,  0.,  5.],
        [ 5.,  6.,  7.]],

       [[ 6.,  2.,  0.],
        [ 3.,  7.,  5.],
        [ 0.,  0.,  7.]]])

In [15]:
print(a.shape)
print((a*(a>0)).shape)
print(a.dot((a>0)).shape)

(2, 3, 3)
(2, 3, 3)
(2, 3, 2, 3)


In [40]:
b = np.arange(10)
print(a.argmax(axis=1))
print(b[a.argmax(axis=1)])


[[2 2 2]
 [0 1 2]]
[[2 2 2]
 [0 1 2]]
