In [1]:
import numpy as np

In [2]:
x = np.array([[1,3,5], 
    [3,5,6],
    [3,18,-10],
    [12,3,1]])
x.shape
np.random.rand()


0.22111092898963436

In [3]:
print(np.random.rand(*x.shape))
(lambda x: np.random.rand(x))(3)
print(*x.shape)

[[ 0.003807    0.94368006  0.6458713 ]
 [ 0.75837344  0.50947076  0.24657162]
 [ 0.31019385  0.64821197  0.37024969]
 [ 0.13153015  0.52713024  0.86372156]]
4 3


In [4]:
import tensorflow as tf


ModuleNotFoundError: No module named 'tensorflow'

In [7]:
import sys
print(sys.version)

3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


In [8]:
import types
def imports():
    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            yield val.__name__
list(imports())

['builtins', 'builtins', 'IPython.core.shadowns', 'numpy', 'sys', 'types']