In [8]:
l = [1,2,3,4,3,3,3,6,7,1,1,9,3,2]
a = (sorted(l,key=l.count,reverse=True))
print(a)
a[0]

[3, 3, 3, 3, 3, 1, 1, 1, 2, 2, 4, 6, 7, 9]


3

In [9]:
import numpy as np
ll = np.array(l)
ll[np.array([1,2,3,4])]

array([2, 3, 4, 3])

In [22]:
test = np.array([[1,2,3],
    [4,2,56],
    [4,5,6],
    [7,8,9]])
train =  np.array([[1,2,3],
    [4,5,6],
    [7,8,9], 
    [2,3,4],
    [3,1,6],
    [23,4,21]])

In [23]:
print(test.shape)
print(train.shape)
print(test[:,np.newaxis].shape)
((train-test[:,np.newaxis])**2).sum(axis=2)

(4, 3)
(6, 3)
(4, 1, 3)


array([[   0,   27,  108,    3,   14,  812],
       [2818, 2509, 2254, 2709, 2502, 1590],
       [  27,    0,   27,   12,   17,  587],
       [ 108,   27,    0,   75,   74,  416]])

In [24]:
test[:,np.newaxis]

array([[[ 1,  2,  3]],

       [[ 4,  2, 56]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]]])

In [25]:
k = {}
k[0] = 9
k[3]= 28
k

{0: 9, 3: 28}

In [26]:
np.array_split(train, 3)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[7, 8, 9],
        [2, 3, 4]]), array([[ 3,  1,  6],
        [23,  4, 21]])]

In [27]:

np.concatenate((train[0:0] , train[1:]) )


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 3,  1,  6],
       [23,  4, 21]])

In [28]:
k_choices = [1, 3, 5, 8, 10, 12, 15, 20, 50, 100]
for i, k in enumerate(k_choices):
    print(i, k)

0 1
1 3
2 5
3 8
4 10
5 12
6 15
7 20
8 50
9 100


In [29]:
np.concatenate(([[1,2,3]], [[2,2,6]]), axis = 0)

array([[1, 2, 3],
       [2, 2, 6]])

In [50]:
print(test.shape)
print(train.shape)
t1 = test.T.reshape(1,3,4)
t2 = train.reshape(6,3,1)
print((t1*t2).sum(axis=1).shape)

(4, 3)
(6, 3)
(6, 4)


In [57]:
np.dot(test, train.T).shape


(4, 6)

In [86]:
import numpy.ma as ma
a = np.array([0,2,1])
b = np.array([3,4,2])
xx = np.array([4,6,7])
ax = ma.masked_array(a, mask=(a>b))
amask = (a>b)
print(ax)
print(amask)
amask*2 - 1 #(false: -1, true: 1)
amask*1

[0 2 1]
[False False False]


array([0, 0, 0])

In [78]:
s = a # let s be the s vectors. s = Wx. 
# make a mask matrix. 
a>b[np.array([2,2,1])]
#((s - si +1 >0)*s).sum() - si # si: the actual s. si: s[trainy[i]]

array([False, False, False], dtype=bool)

In [104]:
bb = [[1,2,1], [2,4,1]]
(bb > b[a,])
c = np.array([1, 0])
np.take(bb, c)

array([2, 1])

In [108]:
print(a)
print(b)
b[a]

[0 2 1]
[3 4 2]


array([3, 2, 4])