In [4]:
l = [1,2,3,4,3,3,3,6,7,1,1,9,3,2]
a = (sorted(l,key=l.count,reverse=True))
print(a)
a[0]

[3, 3, 3, 3, 3, 1, 1, 1, 2, 2, 4, 6, 7, 9]


3

In [2]:
import numpy as np
ll = np.array(l)
ll[np.array([1,2,3,4])]

NameError: name 'l' is not defined

In [12]:
test = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])
train =  np.array([[1,2,3],
    [4,5,6],
    [7,8,9], 
    [2,3,4],
    [3,1,6],
    [23,4,21]])

In [25]:
print(test.shape)
print(train.shape)
print(test[:,np.newaxis].shape)
((train-test[:,np.newaxis])**2).sum(axis=2)

(3, 3)
(6, 3)
(3, 1, 3)


array([[  0,  27, 108,   3,  14, 812],
       [ 27,   0,  27,  12,  17, 587],
       [108,  27,   0,  75,  74, 416]])

In [24]:
test[:,np.newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [26]:
k = {}
k[0] = 9
k[3]= 28
k

{0: 9, 3: 28}

In [47]:
np.array_split(train, 3)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[7, 8, 9],
        [2, 3, 4]]), array([[ 3,  1,  6],
        [23,  4, 21]])]

In [48]:

np.concatenate((train[0:0] , train[1:]) )


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 3,  1,  6],
       [23,  4, 21]])

In [50]:
k_choices = [1, 3, 5, 8, 10, 12, 15, 20, 50, 100]
for i, k in enumerate(k_choices):
    print(i, k)

0 1
1 3
2 5
3 8
4 10
5 12
6 15
7 20
8 50
9 100


In [6]:
np.concatenate(([[1,2,3]], [[2,2,6]]), axis = 0)

array([[1, 2, 3],
       [2, 2, 6]])