In [18]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[3,4,5,6], [4,5,6,7]])
a - b
(a-b).sum(axis=0)

array([-5, -5, -5, -5])

In [8]:
np.sqrt(((a-b)**2).sum(axis=0))

4.0

In [15]:
{x*3 | x for x in a }

{3, 6, 11, 12}

In [30]:
c = np.zeros(b.shape)
c = np.abs(a - b)
(c**2).sum(axis=1)


array([16, 36])

In [37]:
a = np.arange(0, 40, 10)
a = a[:, np.newaxis]
a + b[0]

array([[ 3,  4,  5,  6],
       [13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

In [47]:
d = [[1,2,4,6], [3,6,9,12], [4,6,7,9]]
b

array([[3, 4, 5, 6],
       [4, 5, 6, 7]])

In [54]:
f = b[:, np.newaxis] - d
print(b[:,np.newaxis][0])
print(f)
print(f[0,1])
print(b[0] - d[1])

[[3 4 5 6]]
[[[ 2  2  1  0]
  [ 0 -2 -4 -6]
  [-1 -2 -2 -3]]

 [[ 3  3  2  1]
  [ 1 -1 -3 -5]
  [ 0 -1 -1 -2]]]
[ 0 -2 -4 -6]
[ 0 -2 -4 -6]


ModuleNotFoundError: No module named 'past'